# Generated by Django 3.0.5 on 2020-04-19 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrativa', '0001_initial'),
        ('rhumanos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterios_calidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.TextField(verbose_name='nombre del criterio de costo')),
            ],
        ),
        migrations.CreateModel(
            name='Criterios_costo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.TextField(verbose_name='criterio de calidad')),
            ],
        ),
        migrations.CreateModel(
            name='Criterios_tiempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.TextField(verbose_name='nombre del criterio de tiempo')),
            ],
        ),
        migrations.CreateModel(
            name='Entregables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregable', models.CharField(max_length=25, verbose_name='nombre del entregable')),
            ],
        ),
        migrations.CreateModel(
            name='Normativas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normativa', models.CharField(max_length=20, verbose_name='nombre la normativa')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, verbose_name='codigo del proyecto')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='nombre del proyecto')),
                ('estado', models.CharField(choices=[('EP', 'En proceso'), ('F', 'Finalizado')], max_length=3, verbose_name='estado del proyecto')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativa.Clientes', verbose_name='id del cliente')),
                ('unidad_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativa.Unidades_negocio', verbose_name='id de la unidad de negocios')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='id del empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos_diseño',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(verbose_name='fecha de entrega del proyecto')),
                ('tipo_aprobacion', models.CharField(choices=[('T', 'Teléfono'), ('C', 'Correo'), ('OC', 'Orden Compra'), ('I', 'Interno')], max_length=3, verbose_name='codigo del proyecto')),
                ('direccion_portal', models.CharField(max_length=270, verbose_name='codigo del proyecto')),
                ('fecha_conceptual', models.DateField(verbose_name='fecha de presentacion del diseño conceptual')),
                ('fecha_avance', models.DateField(verbose_name='fecha de presentacion del avance')),
                ('fecha_entrega', models.DateField(verbose_name='fecha de entrega del proyecto')),
                ('horas_ing_proyectadas', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='horas ingeniero proyectadas')),
                ('horas_dib_proyectadas', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='horas ingeniero proyectadas')),
                ('ubicacion_geografica', models.CharField(max_length=270, verbose_name='ubicacion del proyecto')),
                ('categoria_proyecto', models.CharField(choices=[('DC', 'Diseño completo'), ('DA', 'Diseño abreviado'), ('E', 'Estudio'), ('M', 'Mantenimiento')], max_length=3, verbose_name='categoria del proyecto')),
                ('nombre_contacto_principal', models.CharField(max_length=50, verbose_name='nombre del contacto principal')),
                ('telefono_contacto_principal', models.CharField(max_length=25, verbose_name='telefono del contacto principal')),
                ('correo_contacto_principal', models.EmailField(max_length=254, verbose_name='correo del contacto principal')),
                ('nombre_contacto_cobro', models.CharField(blank=True, max_length=50, null=True, verbose_name='nombre del contacto para cobro')),
                ('telefono_contacto_cobro', models.CharField(blank=True, max_length=25, null=True, verbose_name='telefono del contacto para cobro')),
                ('correo_contacto_cobro', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo del contacto para cobro')),
                ('comentario_normativas', models.TextField(blank=True, null=True, verbose_name='comentario de las normativas a cumplir')),
                ('comentario_criterio_costo', models.TextField(blank=True, null=True, verbose_name='comentario de el criterio de costo')),
                ('comentario_criterio_calidad', models.TextField(blank=True, null=True, verbose_name='comentario de el criterio de calidad')),
                ('comentario_entregables_cliente', models.TextField(blank=True, null=True, verbose_name='comentario de los entregables del cliente')),
                ('comentario_entregables_enercom', models.TextField(blank=True, null=True, verbose_name='comentario de los entregables enercom')),
                ('comentario_requisitos_legales', models.TextField(blank=True, null=True, verbose_name='comentario de los requisitos legales')),
                ('criterio_calidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Criterios_calidad', verbose_name='criterio de calidad')),
                ('criterio_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Criterios_costo', verbose_name='criterio de costo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='id del proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos_legales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito', models.CharField(max_length=25, verbose_name='nombre del requisito legal')),
            ],
        ),
        migrations.CreateModel(
            name='riesgos_proyecto_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_riesgo', models.CharField(max_length=255, verbose_name='resumen del riesgo')),
                ('tipo_riesgo', models.CharField(choices=[('TEC', 'Riesgo tecnico'), ('ADMIN', 'Riesgo administrativo'), ('EXT', 'Riesgo externo')], max_length=10, verbose_name='tipo de riesgo')),
                ('impacto', models.CharField(choices=[('A', 'Alto'), ('M', 'Medio'), ('B', 'Bajo')], max_length=3, verbose_name='impacto del riesgo')),
                ('probabilidad', models.CharField(choices=[('A', 'Alta'), ('M', 'Media'), ('B', 'Baja')], max_length=3, verbose_name='probabilidad de ocurrencia del riesgo')),
                ('severidad', models.IntegerField(verbose_name='nivel de severidad del riesgo')),
                ('descripcion_detallada', models.TextField(blank=True, null=True, verbose_name='descripcion detallada del riesgo')),
                ('respuesta_inicial', models.TextField(verbose_name='respuesta inicial ante el riesgo')),
                ('medidas_preventivas', models.TextField(verbose_name='medidas preventivas ante el riesgo')),
                ('proceso_detecta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativa.Unidades_negocio', verbose_name='id de la unidad de negocios')),
                ('proyecto_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos_diseño', verbose_name='id del proyecto de diseño')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos_legales_proyecyo_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos_diseño', verbose_name='id del proyecto de diseño')),
                ('requisito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Requisitos_legales', verbose_name='id del requisito legal')),
            ],
        ),
        migrations.CreateModel(
            name='presupuestos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_total', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='venta total')),
                ('target_material', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='target de materiales')),
                ('target_mo', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='target de mano de obra')),
                ('administrativos', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='target administrativo')),
                ('utilidad_neta', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='utilidad neta')),
                ('porcentaje_utilidad', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='porcentaje de utilidad')),
                ('moneda', models.CharField(default='HNL', max_length=3, verbose_name='moneda')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='id del proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Normativas_proyecto_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Normativas', verbose_name='id de la normativa')),
                ('proyect_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos_diseño', verbose_name='id del proyecto de diseño')),
            ],
        ),
        migrations.CreateModel(
            name='interesados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='id del proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rhumanos.Contratistas', verbose_name='id del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='equipo_trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='id del proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rhumanos.Contratistas', verbose_name='id del usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Entregables_enercom_proyecto_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Entregables', verbose_name='id del entregable')),
                ('proyecto_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos_diseño', verbose_name='id del proyecto de diseño')),
            ],
        ),
        migrations.CreateModel(
            name='Entregables_cliente_proyecto_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='fecha de entrega del entregable')),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Entregables', verbose_name='id del entregable')),
                ('proyecto_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos_diseño', verbose_name='id del proyecto de diseño')),
            ],
        ),
        migrations.CreateModel(
            name='Criterios_tiempo_proyecto_dis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(null=True, verbose_name='comentario del criterio de tiempo')),
                ('criterio_tiempo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proyectos.Criterios_tiempo', verbose_name='id del criterio de tiempo')),
                ('proyecto_dis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos_diseño', verbose_name='id del proyecto de diseño')),
            ],
        ),
        migrations.CreateModel(
            name='contratistas_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.TextField(blank=True, null=True, verbose_name='criterio de seleccion contratista')),
                ('contratista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rhumanos.Contratistas', verbose_name='id del contratista')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='id del proyecto')),
            ],
        ),
    ]
