# Generated by Django 3.0.5 on 2020-04-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregables',
            name='entregable',
            field=models.CharField(max_length=50, verbose_name='nombre del entregable'),
        ),
    ]
