# Generated by Django 3.0.5 on 2020-04-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20200419_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitos_legales',
            name='requisito',
            field=models.CharField(max_length=50, verbose_name='nombre del requisito legal'),
        ),
    ]
