# Generated by Django 3.0.5 on 2020-04-19 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre del cliente')),
                ('rubro', models.CharField(choices=[('instalaciones industriales', 'instalaciones industriales'), ('instalaciones residenciales', 'instalaciones residenciales'), ('primarios', 'primarios')], max_length=100, verbose_name='rubro de trabajo del cliente')),
                ('es_base', models.BooleanField(default=0, verbose_name='si el cliente es base')),
                ('es_duro', models.BooleanField(default=0, verbose_name='si el cliente tiene cuentas pendientes')),
            ],
        ),
        migrations.CreateModel(
            name='Unidades_negocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=100, verbose_name='nombre de la unidad de negocio')),
            ],
        ),
    ]
