# Generated by Django 3.0.5 on 2020-04-19 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratistas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre del contratista')),
                ('area', models.CharField(max_length=100, verbose_name='area de trabajo del contratista')),
                ('telefono_celular', models.CharField(max_length=25, verbose_name='numero de telefono celular del contratista')),
                ('telefono_fijo', models.CharField(blank=True, max_length=25, null=True, verbose_name='numero de telefono fijo del contratista')),
                ('activo', models.BooleanField(default=1, verbose_name='si el contratista esta activo')),
                ('descalificado', models.BooleanField(default=1, verbose_name='si el contratista esta descalificado')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='comentarios sobre el contratista')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_celular', models.CharField(max_length=25, verbose_name='numero de telefono celular del empleado')),
                ('telefono_fijo', models.CharField(blank=True, max_length=25, null=True, verbose_name='numero de telefono fijo del empleado')),
                ('es_gerente', models.BooleanField(default=0, verbose_name='si el empleado es gerente')),
                ('puesto', models.CharField(max_length=50, verbose_name='puesto que ocupa el empleado en la empresa')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativa.Unidades_negocio', verbose_name='id de la unidad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id del empleado')),
            ],
        ),
    ]
